services:
  postgres:
    image: postgres:15-alpine
    container_name: airline_delays_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-airline_delays}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      TZ: ${TZ:-America/Sao_Paulo}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Data Layer/silver/ddl.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  postgres_data: